spring:
  application:
    name: message-service
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: service-group
      enable-auto-commit: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${username}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
topic-to-consume-message: user-topic
server:
  port: 8084


