spring:
  profiles:
    active: local
  application:
    name: message-service
  kafka:
    bootstrap-servers: ${kafka-bootstrap-servers}
    consumer:
      group-id: notification-group
      enable-auto-commit: true
  mail:
    host: ${mail-host}
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
topic-to-consume-message: events-topic
server:
  port: ${server-port}


